### ISSUE TITLE
哥们, 留个联系方式, 问个问题

### ISSUE THREAD

**Issue by queal** [Code-Lonely/code-lonely.github.io#1]
我在 https://github.com/bytedeco/javacv/issues/1831 看到你的留言了, 
咱俩应该干的都是同一个件事情, 都是uniapp-native-plugin 集成 javacv,

javacv那边的issues里说的混淆我也加了, 但是我运行时还会报如下:
java.lang.ClassNotFoundException: org.bytedeco.ffmpeg.avutil.AVBPrint

不知道这个坑你踩了没

**Comment by Code-Lonely** [comment]
我这边直接把混淆关了，一点问题没有

**Comment by queal** [comment]
我的场景是抓流抽帧保存, 在实现的时候, grabber跑的时候, 就会出一堆java.lang.ClassNotFoundException: org.bytedeco.ffmpeg.avutil.AVBPrint, 查了社区, 社区说是可以不管, 但是看到一堆的 ClassNotFoundException 总感觉怪怪的.

感觉javacv对android的支持还是不行, 目前我的需求已经换了别的组件, [ffmpeg-kit](https://github.com/tanersener/ffmpeg-kit)
